spring.application.name=task-manager-api

spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager_api_db
spring.datasource.username=postgres
spring.datasource.password=${LOCAL_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.root=INFO
logging.level.com.taskmanager.api=INFO

spring.config.import=optional:file:.env.properties